# Generated by Django 3.2.6 on 2021-08-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='c_text',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='vote',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_text',
            new_name='question_text',
        ),
    ]
